#!/bin/sh
# Run this script on the server to install dependencies.
# It expects the business card Debian that Prometeus provides.

# Install things
apt-get update
apt-get install git

# Install nginx
echo '
# nginx
deb http://nginx.org/packages/debian/ squeeze nginx
deb-src http://nginx.org/packages/debian/ squeeze nginx
' >> /etc/apt/sources.list
apt-get update
gpg --keyserver keyserver.ubuntu.com --recv-key ABF5BD827BD9BF62
gpg -a --export ABF5BD827BD9BF62 | apt-key add -

apt-get update
apt-get install nginx
update-rc.d nginx defaults

# Add the web information
cp -R web/* /usr/share/nginx/html/
sed -i 's/server_name *localhost\;/server_name rewrite.thomaslevine.com;/' /etc/nginx/conf.d/default.conf

# Helpers
echo 'export PATH="$PATH:~/bin"' >> ~/.bashrc
mkdir -p ~/bin
cp add_rewrite ~/bin
chmod +x ~/bin/add_rewrite
. ~/.bashrc

# Configure rewrites
add_rewrite \
  thomaslevine.com \
  lorena.co.nz \
  deadpeoplebornonmybirthday.com \
  samsara-books.com \
  genderneutralhousing.org \
  bettercoa.ch \
  whitbygroup.com \
  dumptruck.io

# Restart nginx to enable the new configuration.
/etc/init.d/nginx restart
